version: "3.7"
services:
  app:
    build:
      args:
        user: fafa
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: flip
    container_name: flip-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - flip
  db:
    image: mysql:5.7
    container_name: flip-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - flip
  nginx:
    image: nginx:1.17-alpine
    container_name: flip-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - flip

networks:
  flip:
    driver: bridge
